create table if not exists public.rfqs (
  rfq_id text primary key,
  version text not null default '1.0',
  status text not null default 'NEW' check (status in ('NEW','REVIEW','SOURCING','PRICING','PENDING_APPROVAL','QUOTED','CLOSED')),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  language text not null default 'en',
  company text not null,
  contact_name text not null,
  email text not null,
  phone text,
  industry text,
  requirement_type text,
  project_name text,
  delivery_location text,
  required_by date,
  currency text not null default 'AZN',
  priority text not null default 'Normal',
  details text not null,
  attachment jsonb
);

create table if not exists public.rfq_items (
  id bigint generated by default as identity primary key,
  rfq_id text not null references public.rfqs(rfq_id) on delete cascade,
  line_no integer not null,
  description text not null,
  manufacturer text,
  model text,
  quantity numeric,
  unit text,
  technical_specification text,
  status text not null default 'NEW' check (status in ('NEW','SOURCING','PRICED','APPROVED','REJECTED')),
  source_url text,
  source_price numeric,
  markup_percent numeric not null default 10,
  selling_price numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(rfq_id, line_no)
);

create table if not exists public.rfq_status_history (
  id bigint generated by default as identity primary key,
  rfq_id text not null references public.rfqs(rfq_id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_at timestamptz not null default now(),
  changed_by text
);

create index if not exists idx_rfqs_status on public.rfqs(status);
create index if not exists idx_rfqs_submitted_at on public.rfqs(submitted_at desc);
create index if not exists idx_rfq_items_rfq_id on public.rfq_items(rfq_id);
create index if not exists idx_rfq_status_history_rfq_id on public.rfq_status_history(rfq_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rfqs_set_updated_at on public.rfqs;
create trigger rfqs_set_updated_at before update on public.rfqs
for each row execute function public.set_updated_at();

drop trigger if exists rfq_items_set_updated_at on public.rfq_items;
create trigger rfq_items_set_updated_at before update on public.rfq_items
for each row execute function public.set_updated_at();

alter table public.rfqs enable row level security;
alter table public.rfq_items enable row level security;
alter table public.rfq_status_history enable row level security;
